name: AI Blog Post Automation

# Trigger workflow twice daily
on:
  schedule:
    - cron: "0 10,22 * * *"  # 10:00 AM and 10:00 PM UTC
  workflow_dispatch:          # Allows manual triggering

jobs:
  generate-blog:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Generate blog posts
      - name: Generate AI blog post
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: node scripts/generate-blog.js

      # 5️⃣ Commit generated posts
      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add posts/
          git diff-index --quiet HEAD || git commit -m "Automated AI blog post"

      # 6️⃣ Push to repository
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
