name: Generate Blog Posts

on:
  schedule:
    - cron: "0 12 * * *" # every day at noon UTC
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # Fetch full history for better git operations

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'  # Cache npm dependencies

      - name: Install dependencies
        run: npm install

      - name: Generate keywords
        run: npm run generate-keywords

      - name: Generate blog posts
        run: npm run generate-blog

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Reset unintended files
          git reset node_modules package-lock.json || echo "No node_modules or package-lock.json to reset"

          # Add generated files
          git add blog/ keywords.json
          git commit -m "Auto-generate blog posts $(date +'%Y-%m-%d %H:%M:%S UTC') [skip ci]" || echo "No changes to commit"

          # Retry logic with stash and rebase
          for i in {1..3}; do
            echo "Attempt $i to push changes..."
            
            # Stash changes to avoid conflicts
            git stash push -m "Auto-generated changes" || echo "Nothing to stash"
            
            # Pull with rebase
            git pull --rebase origin ${{ github.ref_name }} || {
              echo "Rebase pull failed. Will retry in 10 seconds if attempts remain..."
              git stash pop || echo "No stash to pop"
              sleep 10
              continue
            }
            
            # Reapply stashed changes
            git stash pop || echo "No stash to pop"
            
            # Reset unintended files again
            git reset node_modules package-lock.json || echo "No node_modules or package-lock.json to reset"
            
            # Re-add and recommit
            git add blog/ keywords.json
            git commit -m "Auto-generate blog posts $(date +'%Y-%m-%d %H:%M:%S UTC') [skip ci]" || echo "No changes to commit"
            
            # Try to push
            if git push origin HEAD:${{ github.ref_name }}; then
              echo "Successfully pushed on attempt $i"
              exit 0
            else
              echo "Push failed on attempt $i, retrying in 10 seconds..."
              sleep 10
            fi
          done
          
          echo "Failed to push after 3 attempts"
          exit 1
