name: Generate Blog Posts

on:
  schedule:
    - cron: "0 12 * * *" # Every day at noon UTC
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Clean working directory (ignore posts and keywords)
      - name: Clean working directory
        run: git clean -fdx -e posts/ -e keywords.json

      # 5️⃣ Generate keywords
      - name: Generate keywords
        run: node scripts/generate-keywords.js

      # 6️⃣ Generate blog posts
      - name: Generate blog posts
        run: node scripts/generate-blog.js

      # 7️⃣ Commit & push only generated content
      - name: Commit and push generated content
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Only add generated files
          git add posts/ keywords.json

          # Check for changes
          if ! git diff-index --quiet HEAD; then
            # Fetch remote and rebase
            git fetch origin ${{ github.ref_name }}
            git rebase origin/${{ github.ref_name }} || git rebase --abort

            # Commit and push
            git commit -m "Auto-generate blog posts $(date +'%Y-%m-%d %H:%M:%S UTC') [skip ci]"
            git push origin HEAD:${{ github.ref_name }}
          else
            echo "No changes to commit"
          fi
