name: Generate Blog Posts

on:
  schedule:
    - cron: "0 12 * * *" # runs every day at noon UTC
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Generate keywords
      - name: Generate keywords
        run: node scripts/generate-keywords.js

      # 5️⃣ Generate blog posts
      - name: Generate blog posts
        run: node scripts/generate-blog.js

      # 6️⃣ Commit and push generated posts
      - name: Commit and push generated posts
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add posts/ keywords.json
          git commit -m "Auto-generate blog posts [skip ci]" || echo "No changes to commit"
          git pull --rebase origin main
          git push origin main
