name: Generate Blog Posts Safely

on:
  schedule:
    - cron: "0 12 * * *" # every day at noon UTC
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Generate keywords
        run: npm run generate-keywords

      - name: Generate blog posts
        run: npm run generate-blog

      - name: Commit generated content
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

          git add blog/ keywords.json
          git diff --staged --quiet || git commit -m "Auto-generate blog posts $(date +'%Y-%m-%d %H:%M:%S UTC') [skip ci]"

      - name: Push to temporary branch
        if: success()
        run: |
          TEMP_BRANCH="blog-gen-temp-$(date +%s)"
          git checkout -b $TEMP_BRANCH
          git push origin $TEMP_BRANCH

      - name: Merge into main safely
        if: success()
        run: |
          TEMP_BRANCH="blog-gen-temp-$(date +%s)"
          git fetch origin main
          git checkout main
          git merge --no-ff $TEMP_BRANCH -m "Merge auto-generated blog posts [skip ci]"
          git push origin main
