name: Generate Blog Posts

on:
  schedule:
    - cron: "0 12 * * *" # every day at noon UTC
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Generate keywords
        run: node scripts/generate-keywords.js

      - name: Generate blog posts
        run: node scripts/generate-blog.js

      - name: Commit blog posts to temporary branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          TEMP_BRANCH="blog-auto-update"

          # Create or reset temporary branch
          git checkout -B $TEMP_BRANCH

          # Stage only allowed files
          git add posts/ keywords.json

          # Commit changes if any
          git commit -m "Auto-generate blog posts [skip ci]" || echo "No changes to commit"

      - name: Merge blog posts into main safely
        run: |
          git fetch origin main
          git checkout main
          git merge --ff-only blog-auto-update || echo "No new changes to merge"
          git push origin main
