name: Generate Blog Posts

on:
  schedule:
    - cron: "0 12 * * *" # every day at noon UTC
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # Needed for rebase

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Clean working directory
        run: git clean -fdx -e posts/ -e keywords.json

      - name: Generate keywords
        run: npm run generate-keywords

      - name: Generate blog posts
        run: npm run generate-blog

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          # Configure git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Fetch and rebase remote changes
          git fetch origin ${{ github.ref_name }}
          git rebase origin/${{ github.ref_name }} || git rebase --abort

          # Add only generated content
          git add posts/ keywords.json

          # Commit changes if any
          git commit -m "Auto-generate blog posts $(date +'%Y-%m-%d %H:%M:%S UTC') [skip ci]" || echo "No changes to commit"

          # Push changes
          git push origin HEAD:${{ github.ref_name }}
